### ISSUE TITLE
Download step failing on Jenkins

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-idg#57]
### Describe the bug

Looks like the download step is (gracefully) failing on KG-IDG:
https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-idg/job/master/19/

```
Downloading https://data.bioontology.org/ontologies/ATC/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb&download_format=csv to atc.csv.gz
18:52:42  :  95%|█████████▍| 18/19 [04:06<00:13, 13.68s/it]
18:52:42  Traceback (most recent call last):
18:52:42    File "run.py", line 164, in <module>
18:52:42      cli()
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
18:52:42      return self.main(*args, **kwargs)
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
18:52:42      rv = self.invoke(ctx)
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
18:52:42      return _process_result(sub_ctx.command.invoke(sub_ctx))
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
18:52:42      return ctx.invoke(self.callback, **ctx.params)
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
18:52:42      return __callback(*args, **kwargs)
18:52:42    File "run.py", line 38, in download
18:52:42      kg_download(*args, **kwargs)
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/kg_idg/download.py", line 20, in download
18:52:42      download_from_yaml(yaml_file=yaml_file, output_dir=output_dir,
18:52:42    File "/var/lib/jenkins/workspace/nowledge-graph-hub_kg-idg_master/gitrepo/kg_idg/utils/download_utils.py", line 54, in download_from_yaml
18:52:42      with urlopen(req) as response, open(outfile, 'wb') as out_file:  # type: ignore
18:52:42    File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
18:52:42      return opener.open(url, data, timeout)
18:52:42    File "/usr/lib/python3.8/urllib/request.py", line 531, in open
18:52:42      response = meth(req, response)
18:52:42    File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
18:52:42      response = self.parent.error(
18:52:42    File "/usr/lib/python3.8/urllib/request.py", line 569, in error
18:52:42      return self._call_chain(*args)
18:52:42    File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
18:52:42      result = func(*args)
18:52:42    File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
18:52:42      raise HTTPError(req.full_url, code, msg, hdrs, fp)
18:52:42  urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

### To Reproduce

https://build.berkeleybop.io/job/knowledge-graph-hub/job/kg-idg/job/master/19/

### Version

20016c0e97e378429056c202ea5b980c2ecd29cd

### Additional context

Failing gracefully - Jenkins is using cached data from s3 instead of a fresh download

**Comment by caufieldjh** [comment]
I just noticed this as well - looks like BioPortal had an update on ATC, but broke the link we were using.
(It actually looks like many/all of the CSV links return error 500 - e.g. DOID CSV at https://data.bioontology.org/ontologies/DOID/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb&download_format=csv is also broken)

The RDF/TTL format is still available (https://data.bioontology.org/ontologies/ATC/submissions/16/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb) so I may try switching to that, particularly because it looks like BioPortal makes it more consistently available.

Will ping John Graybeal too.

**Comment by caufieldjh** [comment]
KGX does not currently support RDF as a source, and parsing it as generic TTL yields `ERROR:root:Encountered error: ttl in an unrecognized format`

**Comment by caufieldjh** [comment]
Looks like this download is working now. Bioportal folks suspect a temporary caching issue.
